# Generated by Django 5.1.3 on 2024-12-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
